# Import Libraries

In [2]:
# Import Libaries
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

# Functions

In [3]:
# Function to one hot encode selected columns  
def hot_encode_cat_col(dataframe,list_cat_col):
    for col in list_cat_col:    
        dataframe = pd.get_dummies(columns=[col],drop_first=True,data=dataframe) 
    return dataframe

In [13]:
# Function to loop through the column list and drops the columns
def drop_columns(dataframe,col_list):
    for col in col_list:
        dataframe.drop(columns=[col], inplace=True)

# Load Dataset

In [4]:
# Load in Dataset
combined_resale_df = pd.read_csv('../assets/data_clean/resale_combine_clean.csv')

# One Hot Encode Object Column

In [5]:
# view dataframe info()
combined_resale_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 903393 entries, 0 to 903392
Data columns (total 240 columns):
 #    Column                                 Dtype
---   ------                                 -----
 0    town                                   object
 1    flat_type                              object
 2    block                                  object
 3    street_name                            object
 4    storey_range                           object
 5    floor_area_sqm                         float64
 6    flat_model                             object
 7    lease_commence_date                    int64
 8    resale_price                           float64
 9    remaining_lease                        int64
 10   address                                object
 11   longitude                              float64
 12   latitude                               float64
 13   month_fmt                              object
 14   month                                  int64
 15   year                                   int64
 16   planning_area                          object
 17   P1_employed                            float64
 18   P1_unemployed                          float64
 19   P1_inactive                            float64
 20   P2_pre_primary                         float64
 21   P2_primary                             float64
 22   P2_secondary                           float64
 23   P2_post_secondary                      float64
 24   P2_polytechnic                         float64
 25   P2_prof_qualification_diploma          float64
 26   P2_university                          float64
 27   P3_chinese                             float64
 28   P3_malays                              float64
 29   P3_indian                              float64
 30   P3_others                              float64
 31   P4_total                               float64
 32   P4_below_sgd_1000                      float64
 33   P4_no_working_person                   float64
 34   P4_sgd_10000_over                      float64
 35   P4_sgd_10000_to_10999                  float64
 36   P4_sgd_11000_to_11999                  float64
 37   P4_sgd_1000_to_1999                    float64
 38   P4_sgd_12000_to_12999                  float64
 39   P4_sgd_13000_to_13999                  float64
 40   P4_sgd_14000_to_14999                  float64
 41   P4_sgd_15000_to_17499                  float64
 42   P4_sgd_17500_to_19999                  float64
 43   P4_sgd_20000_over                      float64
 44   P4_sgd_2000_to_2999                    float64
 45   P4_sgd_3000_to_3999                    float64
 46   P4_sgd_4000_to_4999                    float64
 47   P4_sgd_5000_to_5999                    float64
 48   P4_sgd_6000_to_6999                    float64
 49   P4_sgd_7000_to_7999                    float64
 50   P4_sgd_8000_over                       float64
 51   P4_sgd_8000_to_8999                    float64
 52   P4_sgd_9000_to_9999                    float64
 53   P5_no_family_nucleus                   float64
 54   P5_ofn_1_gen                           float64
 55   P5_ofn_2_gen                           float64
 56   P5_ofn_3_more_gen                      float64
 57   P5_tfn_1to2_gen                        float64
 58   P5_tfn_3_more_gen                      float64
 59   P5_three_more_fam_nucleus              float64
 60   P6_total                               float64
 61   P6_below_sgd_1000                      float64
 62   P6_sgd_10000_to_10999                  float64
 63   P6_sgd_11000_to_11999                  float64
 64   P6_sgd_12000_over                      float64
 65   P6_sgd_1000_to_1499                    float64
 66   P6_sgd_1000_to_1999                    float64
 67   P6_sgd_2000_to_2499                    float64
 68   P6_sgd_2500_to_2999                    float64
 69   P6_sgd_3000_to_3999                    float64
 70   P6_sgd_4000_to_4999                    float64
 71   P6_sgd_5000_to_5999                    float64
 72   P6_sgd_6000_over                       float64
 73   P6_sgd_6000_to_6999                    float64
 74   P6_sgd_7000_to_7999                    float64
 75   P6_sgd_8000_over                       float64
 76   P6_sgd_8000_to_8999                    float64
 77   P6_sgd_9000_to_9999                    float64
 78   P6_sgd_1000_to_1999.1                  float64
 79   P6_sgd_2000_to_2999                    float64
 80   P6_sgd_12000_14999                     float64
 81   P6_sgd_15000_over                      float64
 82   P7_manufacturing                       float64
 83   P7_construction                        float64
 84   P7_wholesale_retail_trade              float64
 85   P7_transportation_storage              float64
 86   P7_accommodation_food_services         float64
 87   P7_information_communications          float64
 88   P7_financial_insurance_services        float64
 89   P7_real_estate_services                float64
 90   P7_professional_services               float64
 91   P7_admin_support_services              float64
 92   P7_public_admin_education              float64
 93   P7_health_social_services              float64
 94   P7_arts_entertainment_recreation       float64
 95   P7_other_comm_social_personal          float64
 96   P7_others                              float64
 97   P7_hotels_restaurants                  float64
 98   P7_transport_communications            float64
 99   P7_business_services                   float64
 100  P7_other_services_industries           float64
 101  P8_no_literate                         float64
 102  P8_l1_chi                              float64
 103  P8_l1_eng                              float64
 104  P8_l1_mal                              float64
 105  P8_l1_tam                              float64
 106  P8_l1_non_off                          float64
 107  P8_l2_eng_chi                          float64
 108  P8_l2_eng_mal                          float64
 109  P8_l2_eng_tam                          float64
 110  P8_l2_other_two                        float64
 111  P8_l3_eng_chi_mal                      float64
 112  P8_l3_eng_mal_tam                      float64
 113  P8_l3_other_three                      float64
 114  P8_l2_eng_non_off                      float64
 115  P9_no_literate                         float64
 116  P9_l1_chi                              float64
 117  P9_l1_eng                              float64
 118  P9_l1_mal                              float64
 119  P9_l1_tam                              float64
 120  P9_l1_non_off                          float64
 121  P9_l2_eng_chi                          float64
 122  P9_l2_eng_mal                          float64
 123  P9_l2_eng_tam                          float64
 124  P9_l2_other_two                        float64
 125  P9_l3_eng_chi_mal                      float64
 126  P9_l3_eng_mal_tam                      float64
 127  P9_l3_other_three                      float64
 128  P9_l2_eng_non_off                      float64
 129  P10_bus                                float64
 130  P10_mrt                                float64
 131  P10_mrt_bus                            float64
 132  P10_mrt_car                            float64
 133  P10_mrt_other                          float64
 134  P10_taxi                               float64
 135  P10_car                                float64
 136  P10_pvt_chartered_bus                  float64
 137  P10_lorry_pickup                       float64
 138  P10_motorcycle_scooter                 float64
 139  P10_others                             float64
 140  P10_no_transport_required              float64
 141  P10_other_combi_mrt_or_bus             float64
 142  P10_mrt_lrt_only                       float64
 143  P10_mrt_lrt_and_bus                    float64
 144  P10_other_combi_mrt_lrt_or_bus         float64
 145  P10_taxi_pvt_hire_car_only             float64
 146  P10_pvt_chartered_bus_van              float64
 147  P11_bus                                float64
 148  P11_mrt                                float64
 149  P11_mrt_bus                            float64
 150  P11_mrt_car                            float64
 151  P11_mrt_other                          float64
 152  P11_taxi                               float64
 153  P11_car                                float64
 154  P11_pvt_chartered_bus                  float64
 155  P11_lorry_pickup                       float64
 156  P11_motorcycle_scooter                 float64
 157  P11_others                             float64
 158  P11_no_transport_required              float64
 159  P11_other_combi_mrt_or_bus             float64
 160  P11_mrt_lrt_only                       float64
 161  P11_mrt_lrt_and_bus                    float64
 162  P11_other_combi_mrt_lrt_or_bus         float64
 163  P11_taxi_pvt_hire_car_only             float64
 164  P11_pvt_chartered_bus_van              float64
 165  P12_age_0_4                            float64
 166  P12_age_5_9                            float64
 167  P12_age_10_14                          float64
 168  P12_age_15_19                          float64
 169  P12_age_20_24                          float64
 170  P12_age_25_29                          float64
 171  P12_age_30_34                          float64
 172  P12_age_35_39                          float64
 173  P12_age_40_44                          float64
 174  P12_age_45_49                          float64
 175  P12_age_50_54                          float64
 176  P12_age_55_59                          float64
 177  P12_age_60_64                          float64
 178  P12_age_65_69                          float64
 179  P12_age_70_74                          float64
 180  P12_age_75_79                          float64
 181  P12_age_80_84                          float64
 182  P12_age_85_over                        float64
 183  P13_no_religion                        float64
 184  P13_buddhism                           float64
 185  P13_taoism                             float64
 186  P13_islam                              float64
 187  P13_hinduism                           float64
 188  P13_sikhism                            float64
 189  P13_catholic_christian                 float64
 190  P13_other_christians                   float64
 191  P13_other_religions                    float64
 192  P14_english                            float64
 193  P14_mandarin                           float64
 194  P14_chinese_dialects                   float64
 195  P14_malay                              float64
 196  P14_tamil                              float64
 197  P14_other_indian_languages             float64
 198  P14_others                             float64
 199  P14_eng_mand                           float64
 200  P14_eng_chn_dlt                        float64
 201  P14_eng_mly                            float64
 202  P14_eng_oth_ind_lang                   float64
 203  P14_eng_oth_lang                       float64
 204  P14_mand_eng                           float64
 205  P14_mand_chn_dlt                       float64
 206  P14_mand_oth_lang                      float64
 207  P14_chn_dlt_eng                        float64
 208  P14_chn_dlt_mand                       float64
 209  P14_chn_dlt_oth_lang                   float64
 210  P14_mly_eng                            float64
 211  P14_mly_oth_lang                       float64
 212  P14_tml_eng                            float64
 213  P14_tml_oth_lang                       float64
 214  P14_oth_ind_lang_eng                   float64
 215  P14_oth_ind_lang_oth_lang              float64
 216  P14_oth_lang_eng                       float64
 217  P14_oth_ind_lang_oth_lang.1            float64
 218  P14_oth_lang_oth_non_eng_lang          float64
 219  P14_eng_tml                            float64
 220  P15_owner                              float64
 221  P15_tenant                             float64
 222  P15_others                             float64
 223  P16_hdb_1_and_2_room_flats             float64
 224  P16_hdb_3_room_flats                   float64
 225  P16_hdb_4_room_flats                   float64
 226  P16_hdb_5_room_and_executive_flats     float64
 227  P16_condominiums_and_other_apartments  float64
 228  P16_landed_properties                  float64
 229  P16_others                             float64
 230  P16_total_hdb                          float64
 231  P17_hdb_1_and_2_room_flats             float64
 232  P17_hdb_3_room_flats                   float64
 233  P17_hdb_4_room_flats                   float64
 234  P17_hdb_5_room_and_executive_flats     float64
 235  P17_condominiums_and_other_apartments  float64
 236  P17_landed_properties                  float64
 237  P17_others                             float64
 238  P17_total_hdb                          float64
 239  P17_total                              float64
dtypes: float64(227), int64(4), object(9)
memory usage: 1.6+ GB

In [9]:
# Get columns with datatype object
string_columns = combined_resale_df.select_dtypes(include=['object']).columns.tolist()
string_columns

['town',
 'flat_type',
 'block',
 'street_name',
 'storey_range',
 'flat_model',
 'address',
 'month_fmt',
 'planning_area']

In [10]:
# View the number of unique value for each column value to decide what to encode
# combined_resale_df['town'].unique()

for string_col in string_columns:
    print(string_col,": ", len(combined_resale_df[string_col].unique()))

town :  27
flat_type :  8
block :  2670
street_name :  582
storey_range :  25
flat_model :  34
address :  9750
month_fmt :  403
planning_area :  34

In [12]:
# view first 2 rows of data
combined_resale_df.head(2)

,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,remaining_lease,address,longitude,latitude,month_fmt,month,year,planning_area,P1_employed,P1_unemployed,P1_inactive,P2_pre_primary,P2_primary,P2_secondary,P2_post_secondary,P2_polytechnic,P2_prof_qualification_diploma,P2_university,P3_chinese,P3_malays,P3_indian,P3_others,P4_total,P4_below_sgd_1000,P4_no_working_person,P4_sgd_10000_over,P4_sgd_10000_to_10999,P4_sgd_11000_to_11999,P4_sgd_1000_to_1999,P4_sgd_12000_to_12999,P4_sgd_13000_to_13999,P4_sgd_14000_to_14999,P4_sgd_15000_to_17499,P4_sgd_17500_to_19999,P4_sgd_20000_over,P4_sgd_2000_to_2999,P4_sgd_3000_to_3999,P4_sgd_4000_to_4999,P4_sgd_5000_to_5999,P4_sgd_6000_to_6999,P4_sgd_7000_to_7999,P4_sgd_8000_over,P4_sgd_8000_to_8999,P4_sgd_9000_to_9999,P5_no_family_nucleus,P5_ofn_1_gen,P5_ofn_2_gen,P5_ofn_3_more_gen,P5_tfn_1to2_gen,P5_tfn_3_more_gen,P5_three_more_fam_nucleus,P6_total,P6_below_sgd_1000,P6_sgd_10000_to_10999,P6_sgd_11000_to_11999,P6_sgd_12000_over,P6_sgd_1000_to_1499,P6_sgd_1000_to_1999,P6_sgd_2000_to_2499,P6_sgd_2500_to_2999,P6_sgd_3000_to_3999,P6_sgd_4000_to_4999,P6_sgd_5000_to_5999,P6_sgd_6000_over,P6_sgd_6000_to_6999,P6_sgd_7000_to_7999,P6_sgd_8000_over,P6_sgd_8000_to_8999,P6_sgd_9000_to_9999,P6_sgd_1000_to_1999.1,P6_sgd_2000_to_2999,P6_sgd_12000_14999,P6_sgd_15000_over,P7_manufacturing,P7_construction,P7_wholesale_retail_trade,P7_transportation_storage,P7_accommodation_food_services,P7_information_communications,P7_financial_insurance_services,P7_real_estate_services,P7_professional_services,P7_admin_support_services,P7_public_admin_education,P7_health_social_services,P7_arts_entertainment_recreation,P7_other_comm_social_personal,P7_others,P7_hotels_restaurants,P7_transport_communications,P7_business_services,P7_other_services_industries,P8_no_literate,P8_l1_chi,P8_l1_eng,P8_l1_mal,P8_l1_tam,P8_l1_non_off,P8_l2_eng_chi,P8_l2_eng_mal,P8_l2_eng_tam,P8_l2_other_two,P8_l3_eng_chi_mal,P8_l3_eng_mal_tam,P8_l3_other_three,P8_l2_eng_non_off,P9_no_literate,P9_l1_chi,P9_l1_eng,P9_l1_mal,P9_l1_tam,P9_l1_non_off,P9_l2_eng_chi,P9_l2_eng_mal,P9_l2_eng_tam,P9_l2_other_two,P9_l3_eng_chi_mal,P9_l3_eng_mal_tam,P9_l3_other_three,P9_l2_eng_non_off,P10_bus,P10_mrt,P10_mrt_bus,P10_mrt_car,P10_mrt_other,P10_taxi,P10_car,P10_pvt_chartered_bus,P10_lorry_pickup,P10_motorcycle_scooter,P10_others,P10_no_transport_required,P10_other_combi_mrt_or_bus,P10_mrt_lrt_only,P10_mrt_lrt_and_bus,P10_other_combi_mrt_lrt_or_bus,P10_taxi_pvt_hire_car_only,P10_pvt_chartered_bus_van,P11_bus,P11_mrt,P11_mrt_bus,P11_mrt_car,P11_mrt_other,P11_taxi,P11_car,P11_pvt_chartered_bus,P11_lorry_pickup,P11_motorcycle_scooter,P11_others,P11_no_transport_required,P11_other_combi_mrt_or_bus,P11_mrt_lrt_only,P11_mrt_lrt_and_bus,P11_other_combi_mrt_lrt_or_bus,P11_taxi_pvt_hire_car_only,P11_pvt_chartered_bus_van,P12_age_0_4,P12_age_5_9,P12_age_10_14,P12_age_15_19,P12_age_20_24,P12_age_25_29,P12_age_30_34,P12_age_35_39,P12_age_40_44,P12_age_45_49,P12_age_50_54,P12_age_55_59,P12_age_60_64,P12_age_65_69,P12_age_70_74,P12_age_75_79,P12_age_80_84,P12_age_85_over,P13_no_religion,P13_buddhism,P13_taoism,P13_islam,P13_hinduism,P13_sikhism,P13_catholic_christian,P13_other_christians,P13_other_religions,P14_english,P14_mandarin,P14_chinese_dialects,P14_malay,P14_tamil,P14_other_indian_languages,P14_others,P14_eng_mand,P14_eng_chn_dlt,P14_eng_mly,P14_eng_oth_ind_lang,P14_eng_oth_lang,P14_mand_eng,P14_mand_chn_dlt,P14_mand_oth_lang,P14_chn_dlt_eng,P14_chn_dlt_mand,P14_chn_dlt_oth_lang,P14_mly_eng,P14_mly_oth_lang,P14_tml_eng,P14_tml_oth_lang,P14_oth_ind_lang_eng,P14_oth_ind_lang_oth_lang,P14_oth_lang_eng,P14_oth_ind_lang_oth_lang.1,P14_oth_lang_oth_non_eng_lang,P14_eng_tml,P15_owner,P15_tenant,P15_others,P16_hdb_1_and_2_room_flats,P16_hdb_3_room_flats,P16_hdb_4_room_flats,P16_hdb_5_room_and_executive_flats,P16_condominiums_and_other_apartments,P16_landed_properties,P16_others,P16_total_hdb,P17_hdb_1_and_2_room_flats,P17_hdb_3_room_flats,P17_hdb_4_room_flats,P17_hdb_5_room_and_executive_flats,P17_condominiums_and_other_apartments,P17_landed_properties,P17_others,P17_total_hdb,P17_total
0,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,10 TO 12,31.0,IMPROVED,1977,9000.0,86,309 ANG MO KIO AVE 1,0.0,0.0,1990-01-01,1,1990,ANG MO KIO,45563.5,2655.0,27095.875,2552.75,11249.25,8158.75,2339.75,3003.5,330.5,3142.5,71056.375,6430.0,6819.375,1788.625,59156.5,3787.75,7155.5,3034.25,1111.75,898.75,5814.0,740.75,656.25,714.0,1215.25,960.25,3141.5,5359.0,5061.25,4255.0,3745.25,3038.5,2787.0,2198.25,1813.0,1644.25,13690.5,7779.25,31439.25,3184.25,561.5,1581.75,70.25,91126.75,9787.0,1309.25,901.25,2150.0,8757.25,3591.75,6900.75,5480.0,11506.25,7955.25,6081.75,2084.0,3918.5,2753.75,2741.75,1623.0,1199.5,3591.75,2603.5,809.25,1577.25,11603.25,5233.5,14966.75,5323.5,5699.75,3072.25,6234.0,1795.25,4734.0,4336.0,8560.0,3844.75,1279.75,2696.0,818.5,1603.75,2388.25,2614.25,4323.75,9657.25,31971.0,17941.0,1850.0,704.0,245.75,63916.5,10456.25,5176.0,415.25,2825.25,550.5,938.75,1974.25,9657.25,31971.0,17941.0,1850.0,704.0,245.75,63916.5,10456.25,5176.0,415.25,2825.25,550.5,938.75,1974.25,9146.75,1071.25,3033.5,35.25,6.25,31.75,3337.25,2153.5,42.0,91.0,881.5,8364.0,275.0,356.5,1380.75,65.0,23.75,381.75,18380.75,8174.0,14574.0,264.0,196.75,757.25,18259.25,2545.25,2125.0,2937.0,3074.0,7943.25,1100.0,2672.25,6190.0,412.75,551.0,391.75,3667.5,4240.0,4477.5,4941.25,5498.75,6362.5,6385.0,6685.0,6831.25,7022.5,6803.75,6157.5,5636.25,4516.25,3328.75,2158.75,1383.75,1035.0,26220.0,57950.75,20286.25,12053.5,6639.5,276.5,10873.25,15932.75,370.75,36190.5,47992.75,29666.25,9490.0,4878.75,603.5,746.25,9152.5,1375.75,1037.0,248.0,332.25,4856.0,3800.0,73.0,540.25,2491.25,180.0,1081.0,28.0,766.75,14.75,153.5,67.75,152.0,67.75,90.5,980.0,51543.5,7110.75,477.75,4978.5,25559.5,14134.25,6104.75,3984.75,4058.0,337.25,50777.0,11307.5,67050.0,46210.0,21330.0,11130.0,15835.0,1385.0,145890.0,174245.0
1,ANG MO KIO,1 ROOM,309,ANG MO KIO AVE 1,04 TO 06,31.0,IMPROVED,1977,6000.0,86,309 ANG MO KIO AVE 1,0.0,0.0,1990-01-01,1,1990,ANG MO KIO,45563.5,2655.0,27095.875,2552.75,11249.25,8158.75,2339.75,3003.5,330.5,3142.5,71056.375,6430.0,6819.375,1788.625,59156.5,3787.75,7155.5,3034.25,1111.75,898.75,5814.0,740.75,656.25,714.0,1215.25,960.25,3141.5,5359.0,5061.25,4255.0,3745.25,3038.5,2787.0,2198.25,1813.0,1644.25,13690.5,7779.25,31439.25,3184.25,561.5,1581.75,70.25,91126.75,9787.0,1309.25,901.25,2150.0,8757.25,3591.75,6900.75,5480.0,11506.25,7955.25,6081.75,2084.0,3918.5,2753.75,2741.75,1623.0,1199.5,3591.75,2603.5,809.25,1577.25,11603.25,5233.5,14966.75,5323.5,5699.75,3072.25,6234.0,1795.25,4734.0,4336.0,8560.0,3844.75,1279.75,2696.0,818.5,1603.75,2388.25,2614.25,4323.75,9657.25,31971.0,17941.0,1850.0,704.0,245.75,63916.5,10456.25,5176.0,415.25,2825.25,550.5,938.75,1974.25,9657.25,31971.0,17941.0,1850.0,704.0,245.75,63916.5,10456.25,5176.0,415.25,2825.25,550.5,938.75,1974.25,9146.75,1071.25,3033.5,35.25,6.25,31.75,3337.25,2153.5,42.0,91.0,881.5,8364.0,275.0,356.5,1380.75,65.0,23.75,381.75,18380.75,8174.0,14574.0,264.0,196.75,757.25,18259.25,2545.25,2125.0,2937.0,3074.0,7943.25,1100.0,2672.25,6190.0,412.75,551.0,391.75,3667.5,4240.0,4477.5,4941.25,5498.75,6362.5,6385.0,6685.0,6831.25,7022.5,6803.75,6157.5,5636.25,4516.25,3328.75,2158.75,1383.75,1035.0,26220.0,57950.75,20286.25,12053.5,6639.5,276.5,10873.25,15932.75,370.75,36190.5,47992.75,29666.25,9490.0,4878.75,603.5,746.25,9152.5,1375.75,1037.0,248.0,332.25,4856.0,3800.0,73.0,540.25,2491.25,180.0,1081.0,28.0,766.75,14.75,153.5,67.75,152.0,67.75,90.5,980.0,51543.5,7110.75,477.75,4978.5,25559.5,14134.25,6104.75,3984.75,4058.0,337.25,50777.0,11307.5,67050.0,46210.0,21330.0,11130.0,15835.0,1385.0,145890.0,174245.0

- Observed that block, street name and address has high unique values.
    - These columns will be dropped as location is covered by "planning_area"
- mth_format will be drop as there is already year and month column

In [14]:
# Drop columns
col_to_drop = ['block', 'street_name', 'address',  'month_fmt']
drop_columns(combined_resale_df,col_to_drop)

In [18]:
# Check that the columns has been dropped and update string_columns
string_columns = combined_resale_df.select_dtypes(include=['object']).columns.tolist()
string_columns

['town', 'flat_type', 'storey_range', 'flat_model', 'planning_area']

- Observed that the columns has been dropped
- Next: proceed with one hot encoding for remaining columns

In [19]:
# create a copy of dataframe for one hot encoding
combined_resale_df_copy = combined_resale_df.copy()

# One Hot Encode all String Columns
combined_resale_df_copy = hot_encode_cat_col(combined_resale_df_copy,string_columns)

In [20]:
# Check that there are no more string columns
combined_resale_df_copy.select_dtypes(include=['object']).columns.tolist()

[]

- Validated that there are no more string columns where dtype is object

# Export Dataset for Modelling

In [21]:
# export coordinateList to csv
combined_resale_df_copy.to_csv('../assets/data_clean/resale_combine_encode_clean.csv', encoding='utf-8', index=False)

# export as pickle file
combined_resale_df_copy.to_pickle('../assets/data_clean/resale_combine_encode_clean.pkl')

- Observed that dataset has been exported

- Data will first be exported for Modelling to retrieve a baseline model for comparision. Further analysis of the dataset will be done in the subsequent notebook.